# Additional site settings, with more excludes to omit various larger content,
# like the javadocs, and also older release content, only leaving the smaller
# subset more typically [live-]updated, giving a much faster [re-]build.

# These need to be exact paths, not wildcards.
exclude: [
vendor,
components/classic/documentation/maven/apidocs,
components/cms/api_docs,
components/nms/msdoc
]
